// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: producto.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Objeto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Producto    string `protobuf:"bytes,2,opt,name=producto,proto3" json:"producto,omitempty"`
	Valor       int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Tienda      string `protobuf:"bytes,4,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Destino     string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Prioritario int32  `protobuf:"varint,6,opt,name=prioritario,proto3" json:"prioritario,omitempty"`
}

func (x *Objeto) Reset() {
	*x = Objeto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_producto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Objeto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Objeto) ProtoMessage() {}

func (x *Objeto) ProtoReflect() protoreflect.Message {
	mi := &file_producto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Objeto.ProtoReflect.Descriptor instead.
func (*Objeto) Descriptor() ([]byte, []int) {
	return file_producto_proto_rawDescGZIP(), []int{0}
}

func (x *Objeto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Objeto) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *Objeto) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Objeto) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *Objeto) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *Objeto) GetPrioritario() int32 {
	if x != nil {
		return x.Prioritario
	}
	return 0
}

type Serie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serie int32 `protobuf:"varint,1,opt,name=serie,proto3" json:"serie,omitempty"`
}

func (x *Serie) Reset() {
	*x = Serie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_producto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Serie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Serie) ProtoMessage() {}

func (x *Serie) ProtoReflect() protoreflect.Message {
	mi := &file_producto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Serie.ProtoReflect.Descriptor instead.
func (*Serie) Descriptor() ([]byte, []int) {
	return file_producto_proto_rawDescGZIP(), []int{1}
}

func (x *Serie) GetSerie() int32 {
	if x != nil {
		return x.Serie
	}
	return 0
}

type Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *Estado) Reset() {
	*x = Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_producto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_producto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_producto_proto_rawDescGZIP(), []int{2}
}

func (x *Estado) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type ActEstado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seguimiento int32  `protobuf:"varint,1,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
	Estado      string `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	IdCamion    int32  `protobuf:"varint,3,opt,name=idCamion,proto3" json:"idCamion,omitempty"`
}

func (x *ActEstado) Reset() {
	*x = ActEstado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_producto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActEstado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActEstado) ProtoMessage() {}

func (x *ActEstado) ProtoReflect() protoreflect.Message {
	mi := &file_producto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActEstado.ProtoReflect.Descriptor instead.
func (*ActEstado) Descriptor() ([]byte, []int) {
	return file_producto_proto_rawDescGZIP(), []int{3}
}

func (x *ActEstado) GetSeguimiento() int32 {
	if x != nil {
		return x.Seguimiento
	}
	return 0
}

func (x *ActEstado) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ActEstado) GetIdCamion() int32 {
	if x != nil {
		return x.IdCamion
	}
	return 0
}

type InfoPaquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo        string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor       int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen      string `protobuf:"bytes,4,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino     string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Intentos    int32  `protobuf:"varint,6,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Seguimiento int32  `protobuf:"varint,7,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
}

func (x *InfoPaquete) Reset() {
	*x = InfoPaquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_producto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoPaquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoPaquete) ProtoMessage() {}

func (x *InfoPaquete) ProtoReflect() protoreflect.Message {
	mi := &file_producto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoPaquete.ProtoReflect.Descriptor instead.
func (*InfoPaquete) Descriptor() ([]byte, []int) {
	return file_producto_proto_rawDescGZIP(), []int{4}
}

func (x *InfoPaquete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InfoPaquete) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *InfoPaquete) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *InfoPaquete) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *InfoPaquete) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *InfoPaquete) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *InfoPaquete) GetSeguimiento() int32 {
	if x != nil {
		return x.Seguimiento
	}
	return 0
}

type Envio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seguimiento int32  `protobuf:"varint,1,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
	Intentos    int32  `protobuf:"varint,2,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Estado      string `protobuf:"bytes,3,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *Envio) Reset() {
	*x = Envio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_producto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Envio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envio) ProtoMessage() {}

func (x *Envio) ProtoReflect() protoreflect.Message {
	mi := &file_producto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envio.ProtoReflect.Descriptor instead.
func (*Envio) Descriptor() ([]byte, []int) {
	return file_producto_proto_rawDescGZIP(), []int{5}
}

func (x *Envio) GetSeguimiento() int32 {
	if x != nil {
		return x.Seguimiento
	}
	return 0
}

func (x *Envio) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *Envio) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

var File_producto_proto protoreflect.FileDescriptor

var file_producto_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x9e, 0x01, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x74, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x61, 0x72,
	0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69,
	0x74, 0x61, 0x72, 0x69, 0x6f, 0x22, 0x1d, 0x0a, 0x05, 0x53, 0x65, 0x72, 0x69, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x65, 0x72, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x65, 0x72, 0x69, 0x65, 0x22, 0x20, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x61, 0x0a, 0x09, 0x41, 0x63, 0x74, 0x45, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e,
	0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x64, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x69, 0x64, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x22, 0xb7, 0x01, 0x0a, 0x0b, 0x69, 0x6e,
	0x66, 0x6f, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65,
	0x6e, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x05, 0x45, 0x6e, 0x76, 0x69, 0x6f, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73,
	0x74, 0x61, 0x64, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x32, 0xec, 0x01, 0x0a, 0x08, 0x50, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x12,
	0x2b, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x50, 0x65, 0x74, 0x69, 0x63,
	0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x74, 0x6f, 0x1a,
	0x09, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x65, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x0b,
	0x50, 0x65, 0x64, 0x69, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x72, 0x69, 0x65, 0x1a, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x10, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a,
	0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63,
	0x74, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x1a, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0c, 0x50, 0x65, 0x64, 0x69, 0x72, 0x50, 0x61,
	0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x74, 0x45, 0x73,
	0x74, 0x61, 0x64, 0x6f, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x50, 0x61,
	0x71, 0x75, 0x65, 0x74, 0x65, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x0d, 0x45, 0x6e, 0x76, 0x69, 0x61,
	0x72, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e,
	0x76, 0x69, 0x6f, 0x1a, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22,
	0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_producto_proto_rawDescOnce sync.Once
	file_producto_proto_rawDescData = file_producto_proto_rawDesc
)

func file_producto_proto_rawDescGZIP() []byte {
	file_producto_proto_rawDescOnce.Do(func() {
		file_producto_proto_rawDescData = protoimpl.X.CompressGZIP(file_producto_proto_rawDescData)
	})
	return file_producto_proto_rawDescData
}

var file_producto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_producto_proto_goTypes = []interface{}{
	(*Objeto)(nil),      // 0: pb.Objeto
	(*Serie)(nil),       // 1: pb.Serie
	(*Estado)(nil),      // 2: pb.Estado
	(*ActEstado)(nil),   // 3: pb.ActEstado
	(*InfoPaquete)(nil), // 4: pb.infoPaquete
	(*Envio)(nil),       // 5: pb.Envio
}
var file_producto_proto_depIdxs = []int32{
	0, // 0: pb.Peticion.RealizarPeticion:input_type -> pb.Objeto
	1, // 1: pb.Peticion.PedirEstado:input_type -> pb.Serie
	3, // 2: pb.Peticion.ActualizarEstado:input_type -> pb.ActEstado
	3, // 3: pb.Peticion.PedirPaquete:input_type -> pb.ActEstado
	5, // 4: pb.Peticion.EnviarPaquete:input_type -> pb.Envio
	1, // 5: pb.Peticion.RealizarPeticion:output_type -> pb.Serie
	2, // 6: pb.Peticion.PedirEstado:output_type -> pb.Estado
	2, // 7: pb.Peticion.ActualizarEstado:output_type -> pb.Estado
	4, // 8: pb.Peticion.PedirPaquete:output_type -> pb.infoPaquete
	2, // 9: pb.Peticion.EnviarPaquete:output_type -> pb.Estado
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_producto_proto_init() }
func file_producto_proto_init() {
	if File_producto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_producto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Objeto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_producto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Serie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_producto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_producto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActEstado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_producto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoPaquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_producto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Envio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_producto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_producto_proto_goTypes,
		DependencyIndexes: file_producto_proto_depIdxs,
		MessageInfos:      file_producto_proto_msgTypes,
	}.Build()
	File_producto_proto = out.File
	file_producto_proto_rawDesc = nil
	file_producto_proto_goTypes = nil
	file_producto_proto_depIdxs = nil
}
